# Site/SEO settings
email: ruben@rubeng.design
baseurl: ""
permalink: /:title/
google_analytics: UA-150076975-1
name: rubeng
title: rubeng.design
description: rubeng.design is a web design and development blog published by Ruben Gutierrez where you can find information & resources about web development and design.  
url: https://rubeng.design
twitter_username: rullbem
default_img:
social:
  - name: twitter
    url: https://twitter.com/rullbem
  - name: github
    url: https://github.com/rullben
  - name: behance
    url: https://www.behance.net/rullbem


# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/S3TM3lIHzmI

# Disqus settings
disqus: 

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Ruben Gutierrez
    bio: Ruben Gutierrez is a web developer who is passionate about making website.
    url: http://rubeng.design

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: ':tag'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
